### ISSUE TITLE
No access to 'svgling.core' functions.

### ISSUE THREAD

**Issue by LLLena2021** [rawlins/svgling#8]
I installed the `svgling` module as described in [`svgling 0.4.0`](https://pypi.org/project/svgling/) and [The `svgling` package](https://rawlins.github.io/svgling/), and ran it on GoogleColab and Command Prompt (Python 3.10.13).

I started running the tutorials step by step as described on [The `svgling` package](https://rawlins.github.io/svgling/) and [`svgling` Manual](https://rawlins.github.io/svgling/manual.html). As soon as the tutorials required access to `svgling.core`  functions, both Colab and Python 3.10.13. have produced an error.

Here is the procedure and the error from Command Prompt (Python 3.10.13):

(scienv) C:\Windows\system32>python
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import svgling
>>> from svgling import draw_tree
>>> svgling.core.reset_defaults()
>>> from svgling.core import node
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'node' from 'svgling.core' (C:\Users\XXXXX\miniconda3\envs\scienv\lib\site-packages\svgling\core.py)

Something similar I have received in Colab. I can provide errors and screenshots if you need those. Please, let me know.

Could you please tell me how to run the following functions:
svgling.core.subscript_node()
svgling.core.cssfont()
*.set_node_style()
svgling.core.TriangleEdge()

I should note that the command `svgling.core.default_options.leaf_nodes_align = True` works perfectly with the sentence `t2` converted in `nltk` (see the Manual). 

Could you please help me?

Best regards,
EP.

**Comment by rawlins** [comment]
Thanks for the report, and sorry for the slow-ish reply. What's happening here is that the web documentation is for the current development (unreleased) version, but these commands install the stable version. I plan to do a 1.0 release this summer which will help clarify this situation, but in the meantime, in colab you should use `!pip install git+https://github.com/rawlins/svgling` to install the version matching the web documentation.

Here's a more complete colab document illustrating this: https://colab.research.google.com/drive/1ncUDlUZGawTujGGsyffNQ7CRirU83Ay6?usp=sharing

**Comment by LLLena2021** [comment]
Dear Rawlins,

Thank you so much for your reply. It has worked with the new version as you recommended.

Regards,
EP.
